services:
  database:
    image: postgres:15.4
    container_name: account_database
    environment:
      - PGPORT=${POSTGRES_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - main
    restart: always

networks:
  main:
    external: true

volumes:
  database:
    driver: local
    driver_opts:
      device: ./database
      type: volume
      o: bind
